import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Save, X, User, Phone, Loader2 } from 'lucide-react';
import { storage } from '../lib/storage';
import { useNotification } from '../context/NotificationContext';
import { db } from '../lib/db';
import type { Grade } from '../types/class';
import type { TeacherFormData } from '../types/teacher';

export default function AddTeacher() {
    const { showSuccess } = useNotification();
    const navigate = useNavigate();
    const { id } = useParams();
    const isEditMode = Boolean(id);
    const [loading, setLoading] = useState(false);
    const [grades, setGrades] = useState<Grade[]>([]);
    const [fetchingGrades, setFetchingGrades] = useState(true);

    const [formData, setFormData] = useState<TeacherFormData>({
        fullName: '',
        gender: 'Male',
        phone: '',
        assignedGrades: []
    });

    const [generatedId, setGeneratedId] = useState('');

    useEffect(() => {
        const loadGrades = async () => {
            setFetchingGrades(true);
            try {
                const data = await db.getGrades();
                setGrades(data);
            } catch (err) {
                console.error('Failed to load grades', err);
            } finally {
                setFetchingGrades(false);
            }
        };
        loadGrades();

        const loadInitialData = async () => {
            if (isEditMode && id) {
                const teachers = await storage.getTeachers();
                const teacher = teachers.find(t => t.id === id);
                if (teacher) {
                    setGeneratedId(teacher.id);
                    setFormData({
                        fullName: teacher.fullName,
                        gender: teacher.gender,
                        phone: teacher.phone,
                        assignedGrades: teacher.assignedGrades
                    });
                }
            } else {
                const nextId = await storage.getNextTeacherIdNumber();
                setGeneratedId(`T${String(nextId).padStart(3, '0')}`);
            }
        };
        loadInitialData();
    }, [isEditMode, id]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);

        try {
            if (isEditMode && id) {
                await storage.updateTeacher(id, formData);
            } else {
                await storage.saveTeacher(formData);
            }
            showSuccess(isEditMode ? 'Teacher updated successfully!' : 'Teacher saved successfully!');
            navigate('/teachers');
        } catch (error) {
            console.error('Failed to save teacher', error);
        } finally {
            setLoading(false);
        }
    };

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const toggleGrade = (grade: string) => {
        setFormData(prev => {
            const current = prev.assignedGrades;
            if (current.includes(grade)) {
                return { ...prev, assignedGrades: current.filter(g => g !== grade) };
            } else {
                return { ...prev, assignedGrades: [...current, grade] };
            }
        });
    };

    return (
        <div className="max-w-2xl mx-auto">
            <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold text-gray-800">
                    {isEditMode ? 'Edit Teacher' : 'Add New Teacher'}
                </h2>
                <button
                    onClick={() => navigate('/teachers')}
                    className="p-2 hover:bg-gray-100 rounded-full text-gray-500 transition-colors"
                >
                    <X size={24} />
                </button>
            </div>

            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 md:p-8">
                <form onSubmit={handleSubmit} className="space-y-6">
                    {/* Auto-generated ID */}
                    <div className="mb-6 bg-blue-50 p-4 rounded-xl flex items-center gap-3 border border-blue-100">
                        <div className="p-2 bg-white rounded-lg shadow-sm text-blue-600">
                            <span className="font-bold font-mono text-lg">{generatedId || '...'}</span>
                        </div>
                        <div>
                            <p className="text-sm text-blue-800 font-medium">Teacher ID</p>
                            <p className="text-xs text-blue-600">Auto-generated by system</p>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 gap-6">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                Full Name <span className="text-red-500">*</span>
                            </label>
                            <div className="relative">
                                <User className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                                <input
                                    type="text"
                                    name="fullName"
                                    required
                                    value={formData.fullName}
                                    onChange={handleChange}
                                    className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-gray-200 focus:border-purple-500 focus:ring-4 focus:ring-purple-500/10 outline-none transition-all"
                                    placeholder="e.g. Abebe Kebede"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                Phone Number <span className="text-red-500">*</span>
                            </label>
                            <div className="relative">
                                <Phone className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                                <input
                                    type="tel"
                                    name="phone"
                                    required
                                    value={formData.phone}
                                    onChange={handleChange}
                                    className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-gray-200 focus:border-purple-500 focus:ring-4 focus:ring-purple-500/10 outline-none transition-all"
                                    placeholder="+251 9..."
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">Gender</label>
                            <div className="flex gap-4">
                                {['Male', 'Female'].map((option) => (
                                    <label key={option} className="flex items-center gap-2 cursor-pointer group">
                                        <input
                                            type="radio"
                                            name="gender"
                                            value={option}
                                            checked={formData.gender === option}
                                            onChange={handleChange}
                                            className="w-4 h-4 text-purple-600 border-gray-300 focus:ring-purple-500"
                                        />
                                        <span className="text-gray-600 group-hover:text-gray-900">{option}</span>
                                    </label>
                                ))}
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                Assigned Grades <span className="text-red-500">*</span>
                            </label>
                            <div className="grid grid-cols-2 md:grid-cols-3 gap-2 p-4 bg-gray-50 rounded-xl border border-gray-100 max-h-48 overflow-y-auto">
                                {fetchingGrades ? (
                                    <div className="col-span-full py-4 text-center text-sm text-gray-500 flex items-center justify-center gap-2">
                                        <Loader2 size={16} className="animate-spin" />
                                        Loading classes...
                                    </div>
                                ) : grades.length === 0 ? (
                                    <div className="col-span-full py-4 text-center text-sm text-red-500">
                                        No classes found. Please create one first.
                                    </div>
                                ) : (
                                    grades.map(grade => (
                                        <label key={grade.id} className="flex items-center gap-2 cursor-pointer p-1">
                                            <input
                                                type="checkbox"
                                                checked={formData.assignedGrades.includes(grade.name)}
                                                onChange={() => toggleGrade(grade.name)}
                                                className="rounded text-purple-600 focus:ring-purple-500"
                                            />
                                            <span className="text-sm text-gray-700">{grade.name}</span>
                                        </label>
                                    ))
                                )}
                            </div>
                            {formData.assignedGrades.length === 0 && (
                                <p className="text-xs text-red-500 mt-1">Please select at least one grade.</p>
                            )}
                        </div>
                    </div>

                    <div className="flex gap-3 pt-6">
                        <button
                            type="button"
                            onClick={() => navigate('/teachers')}
                            className="flex-1 px-4 py-3 bg-gray-100 text-gray-700 rounded-xl font-medium hover:bg-gray-200 transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            disabled={loading || grades.length === 0}
                            className="flex-1 px-4 py-3 bg-primary text-white rounded-xl font-medium hover:bg-primary/90 transition-all shadow-md shadow-purple-200 disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                        >
                            <Save size={20} />
                            {loading ? 'Saving...' : (isEditMode ? 'Update Teacher' : 'Save Teacher')}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
}
